### ISSUE TITLE
New DRNE Run Error

### ISSUE THREAD

**Issue by pixelsaurus** [MRN-Code/coinstac_drne_fsl#5]
Tried to run latest computation in UI and it gave an error that Ross nor I could understand. 

We then ran with copied local state in simulator and got the same error. 

To duplicate. Checkout the 'drne-error' branch and run simulator on it.

**Comment by hvgazula** [comment]
Done. https://github.com/MRN-Code/coinstac_drne_fsl/commit/485bc8838143a8b441aec456cf8f79591c30f417
